// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_active_refresh_token.sql

package database

import (
	"context"
)

const getActiveRefreshToken = `-- name: GetActiveRefreshToken :one
SELECT
          token
          ,created_at
          ,updated_at
          ,user_id
          ,expires_at
          ,revoked_at
FROM      refresh_tokens
WHERE     token = $1
      AND NOW() < expires_at
      AND revoked_at IS NULL
`

func (q *Queries) GetActiveRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
